export const imagePath = {
     '0': require("../../../TarotCardImg/TheFool.png"),  
     '1': require("../../../TarotCardImg/TheMagician.png"),
     '2': require("../../../TarotCardImg/TheHighPriestess.png"),
     '3': require("../../../TarotCardImg/TheEmpress.png"),
     '4': require("../../../TarotCardImg/TheEmperor.png"),
     '5': require("../../../TarotCardImg/TheHierophant.png"),
     '6': require("../../../TarotCardImg/TheLovers.png"),
     '7': require("../../../TarotCardImg/TheChariot.png"),
     '8': require("../../../TarotCardImg/Strength.png"),
     '9': require("../../../TarotCardImg/TheHermit.png"),
     '10': require("../../../TarotCardImg/WheelofFortune.png"),
     '11': require("../../../TarotCardImg/Justice.png"),
     '12': require("../../../TarotCardImg/TheHangedMan.png"),
     '13': require("../../../TarotCardImg/Death.png"),
     '14': require("../../../TarotCardImg/Temperance.png"),
     '15': require("../../../TarotCardImg/TheDevil.png"),
     '16': require("../../../TarotCardImg/TheTower.png"),
     '17': require("../../../TarotCardImg/TheStar.png"),
     '18': require("../../../TarotCardImg/TheMoon.png"),
     '19': require("../../../TarotCardImg/TheSun.png"),
     '20': require("../../../TarotCardImg/Judgement.png"),    
     '21': require("../../../TarotCardImg/TheWorld.png")
     };
    